version: '3'
services:
  portainer:
    image: portainer/portainer-ce:latest
    ports:
      - 9443:9443
    volumes:
      - ./_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    environment:
      VIRTUAL_HOST: portainer.glasno.space
      CERT_NAME: portainer.glasno.space
      HTTPS_METHOD: noredirect
      VIRTUAL_PROTO: https

  frontend-landing:
    image: ghcr.io/glasno/glasno-fe:latest
    ports:
      - 80:3000
      - 443:3000
    restart: unless-stopped
    environment:
      VIRTUAL_HOST: glasno.space
      CERT_NAME: glasno.space
      HTTPS_METHOD: noredirect
      VIRTUAL_PROTO: https
